### ISSUE TITLE
Predicates of the following types do not work: and, or, not

### ISSUE THREAD

**Issue by 4385708alex91** [demyan112rv/mountebank-api-php#10]
Such predicates should be able to include predicates of other types.
http://www.mbtest.org/docs/api/predicates#predicates-and
http://www.mbtest.org/docs/api/predicates#predicates-or
http://www.mbtest.org/docs/api/predicates#predicates-not

**Comment by demyan112rv** [comment]
@4385708alex91 please use new tag https://github.com/demyan112rv/mountebank-api-php/releases/tag/1.11.0

**Comment by 4385708alex91** [comment]
I tested it, unfortunately there are two problems:
1 It is not possible to specify several operators of the same type. For example, inside "AND" specify two 'equals'
2 Specifying setXPath or setJsonPath for 'equals' produces an entry for "AND"

The code I'm writing:
        $predicate1 = (new Predicate(Predicate::OPERATOR_EQUALS))->setConfig(['body' => '3330.00'])->setXPath((new XPath("//*[local-name(.)='Cash']")));
        $predicate2 = (new Predicate(Predicate::OPERATOR_EQUALS))->setConfig(['body' => '.00'])->setXPath((new XPath("//*[local-name(.)='Card']")));

        $predicate = new Predicate(Predicate::OPERATOR_AND);
        $predicate->setConfig([
            $predicate1->getOperator() => $predicate1,
            $predicate2->getOperator() => $predicate2,
        ]);
What I expect:
![image](https://github.com/user-attachments/assets/cbf9240e-a826-4452-a144-55ca1fe93194)
What I get:
![image](https://github.com/user-attachments/assets/80f5a3b6-ab3e-44a8-b38b-5c4c4227f9d0)

**Comment by demyan112rv** [comment]
@4385708alex91 thanks for the testing!
Fixed here https://github.com/demyan112rv/mountebank-api-php/releases/tag/1.11.1

**Comment by 4385708alex91** [comment]
@demyan112rv I checked, everything works fine. Many thanks for the help
