### ISSUE TITLE
Add the ability to edit a stub in an existing imposter

### ISSUE THREAD

**Issue by 4385708alex91** [demyan112rv/mountebank-api-php#9]
https://www.mbtest.org/docs/api/overview#add-stub
POST /imposters/:port/stubs

https://www.mbtest.org/docs/api/overview#change-stub
PUT /imposters/:port/stubs/:stubIndex

https://www.mbtest.org/docs/api/overview#delete-stub
DELETE /imposters/:port/stubs/:stubIndex

**Comment by demyan112rv** [comment]
@4385708alex91 please use the last tag https://github.com/demyan112rv/mountebank-api-php/releases/tag/1.9.0

I have no way to test this code now. If you find any problem, feel free to let me know.

**Comment by 4385708alex91** [comment]
@demyan112rv Unfortunately there is a bug in the getStubsUrl method; you need to use the imposter port instead of the Mountebank port.
Now a line like http://sl-autotests-01:2525/imposters/2525/stubs is being generated and it should be http://sl-autotests-01:2525/imposters/$imposter->getPort()/stubs

**Comment by demyan112rv** [comment]
@4385708alex91 thanks for test. Fixed. I made the stub methods more flexible with the ability to pass a port.
Please try to use tag https://github.com/demyan112rv/mountebank-api-php/releases/tag/1.10.1

**Comment by 4385708alex91** [comment]
I checked, everything works fine. Many thanks for the help
